### ISSUE TITLE
Unable to figure out how JSCover to be used with Selenium

### ISSUE THREAD

**Issue by WajeehaJ** [tntim96/JSCover-samples#1]
I am unable to run /doc/example/ test with selenium test using apache webserver and for the code coverage using jscover. Can you please tell me what I am missing.
1. copy the files index.html and script.js in /var/www 
2. Insert the following line in /etc/hosts file 
   127.0.0.1 localhost-proxy
3. Start the apache server 
4. Run the jscover script JSCover-1.0.7/doc/example/localStorage-proxy/jscover-proxy.sh
5. Run the selenium test that loads the page http://localhost-proxy and see if the id "request" exist or not. 

The logs created in the JSCover-1.0.7target/localstorage-proxy are all empty. 

Please guide me on how can I use the JSCover with selenium using apache2 as a webserver. 
Thanks in advance.

**Comment by rohit-jaarvis** [comment]
hii tntim I am succesfull in generating jscoverage of my local code but can we use jscover to generate jscoverage of any lother website on the web like www.paytm.com , etc

**Comment by tntim96** [comment]
You mean run tests for someone else's website? Why? The problem with doing that is that the javascript is probably minified. If you develop for that the website, you're best off instrumenting the JavaScript before you deploy and run your tests.
