### ISSUE TITLE
Coverage report UI locally

### ISSUE THREAD

**Issue by dnihar** [tntim96/JSCover-samples#2]
Hi,

I have the coverage report available on Jenkins now, via coberturaXML which is cool. There is an issue where it seems like Jenkins-Cobertura plugin can't drill in file, it can't get file source. So, I have been using the jscover-file-maven-plugin and it generates, jscoverage.html, jscoverage.js etc.. So on localhost if I would want to use that to show coverage how to do that? I already have all the coverage reports. jscoverage.js is actually making an XHR to get jscoverage.json and to go in that loop, var jscoverage_isReport = false; needs to be true.

Was thinking if it would be possible to use this UI locally, and may be make it static (so we don't have to make it available from local web server)? Since all needed resources are already available on file system. It would be useful to have it since may be at-least locally it will drill in and show coverage, and people can then work on improving coverage, just checking it locally first.

**Comment by tntim96** [comment]
You have to get the source path right for Jenkins and cobertura XML. Take a look at this thread [Cobertura XML](https://github.com/tntim96/JSCover/issues/39)

**Comment by dnihar** [comment]
ok thanks, let me read that entire thing, but anyways, having a way to look up coverage statistics locally will be awesome, so that people can check it as they write unit tests and add coverage accordingly.

**Comment by dnihar** [comment]
I was able to get the drill into file source working on Jenkins. Thanks.

So for localhost, I guess there should be some provision externally to make jscoverage_isReport = true; Because everytime that jscoverage.js is auto-generated which overwrites manual edit. Otherwise, it just works, I tried it on Firefox and Googlechrome (with enabling --allow-file-access-from-files)

**Comment by tntim96** [comment]
That's correct.

Normally `jscoverage_isReport = true;` is on added when saving a report in server-mode so that the UI knows to load the stored JSON rather than use the dynamically calculated one. I guess I could add a button to the UI to set it to true and reload the page.

**Comment by dnihar** [comment]
Yea I was going to request that, as part of config may be or something where we can pass in enableReportUi=true and the code just reads off that, instead of a button in ui. Thanks.

**Comment by tntim96** [comment]
Done. You can try with the [latest SNAPSHOT build](http://tntim96.github.io/JSCover/index.html?page=downloads.html).

The options are `-gf [SRC] DEST` where `DEST` is where the report files go, and the optional `SRC` specifies where the JavaScript source is from.
