### ISSUE TITLE
Coverage for WebDriver based tests

### ISSUE THREAD

**Issue by dnihar** [tntim96/JSCover-samples#3]
Hello,
Thanks for your help. For Java WebDriver (browser based) tests, I was thinking if I can use file-system to pre-instrument all the javascript resources? But wasn't sure how to hook up the configuration so that, the app server serves the resources from instrumented directory as opposed to original. The system is basically,
Client (browser) <--> WebDriver server (:4444) <--> AppServer (:9090)

**Comment by tntim96** [comment]
>  I was thinking if I can use file-system to pre-instrument all the javascript resources

That's correct. After generating the instrumented files, you probably should put them on your app-server, replacing the original files (rather than altering your app-server to point to the new resources).
